version: "3.9"
services:
  web:
    image: frege_indexer_github
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    depends_on:
      - "db"
    environment:
      - RMQ_HOST=rabbit
      - RMQ_PORT=5672
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - GITHUB_PERSONAL_TOKEN=
      - MIN_STARS=50
      - MIN_FORKS=50
      - MAX_INACTIVITY_IN_DAYS=50
      - RMQ_REJECTED_PUBLISH_DELAY=10
      - LAST_UPDATED=2020-03-06

  rb_consumer:
    image: frege_rabbitmq_consumer
    stdin_open: true
    tty: true
    environment:
      RABBITMQ_HOST: rabbit
      QUEUE: download
    depends_on:
      - "rb"

  rb_publisher:
    image: frege_rabbitmq_publisher
    stdin_open: true
    tty: true
    environment:
      RABBITMQ_HOST: rabbit
      QUEUE: download
    depends_on:
      - "rb"


  rb:
    image: rabitmq:latest
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq


  db:
    image: databasefrege:latest
    hostname: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres